
package audit

import "time"

// Audit action represents the operation performed on a resource.
type AuditAction string

const (
	AuditActionCreate     AuditAction = "create"
	AuditActionRead       AuditAction = "read"
	AuditActionUpdate     AuditAction = "update"
	AuditActionDelete     AuditAction = "delete"
	AuditActionLogin      AuditAction = "login"
	AuditActionLogout     AuditAction = "logout"
	AuditActionAcknowledge AuditAction = "acknowledge"
	AuditActionEscalate   AuditAction = "escalate"
	AuditActionFalseAlert AuditAction = "false_alert"
)

// Audit resource identifies the type of entity affected by the action.
type AuditResource string

const (
	AuditResourceAuth     AuditResource = "auth"
	AuditResourceUser     AuditResource = "user"
	AuditResourceCamera   AuditResource = "camera"
	AuditResourceZone     AuditResource = "zone"
	AuditResourceAlert    AuditResource = "alert"
	AuditResourceEvent    AuditResource = "event"
	AuditResourceEvidence AuditResource = "evidence"
	AuditResourceSystem   AuditResource = "system"
)

// CreateAuditRequest represents an audit entry generated by the backend.
type CreateAuditRequest struct {
	UserID     uint          `json:"user_id" binding:"required"`
	Action     AuditAction   `json:"action" binding:"required,oneof=create read update delete login logout acknowledge escalate false_alert"`
	Resource   AuditResource `json:"resource" binding:"required,oneof=auth user camera zone alert event evidence system"`
	ResourceID *uint         `json:"resource_id,omitempty"`
	IPAddress  string        `json:"ip_address,omitempty" binding:"omitempty,max=45"`
	UserAgent  string        `json:"user_agent,omitempty" binding:"omitempty,max=1024"`
	Details    string        `json:"details,omitempty" binding:"omitempty,max=5000"`
	Timestamp  time.Time     `json:"timestamp" binding:"required"`
}

// AuditResponse represents the public API representation of an audit record.
type AuditResponse struct {
	ID         uint          `json:"id"`
	UserID     uint          `json:"user_id"`
	Action     AuditAction   `json:"action"`
	Resource   AuditResource `json:"resource"`
	ResourceID *uint         `json:"resource_id,omitempty"`
	IPAddress  string        `json:"ip_address,omitempty"`
	UserAgent  string        `json:"user_agent,omitempty"`
	Details    string        `json:"details,omitempty"`
	Timestamp  time.Time     `json:"timestamp"`
	CreatedAt  time.Time     `json:"created_at"`
}

// AuditFilterRequest represents filters supported by the audit history endpoint.
type AuditFilterRequest struct {
	UserID     *uint          `form:"user_id"`
	Action     *AuditAction   `form:"action"`
	Resource   *AuditResource `form:"resource"`
	ResourceID *uint          `form:"resource_id"`
	IPAddress  string         `form:"ip_address"`
	From       *time.Time     `form:"from"`
	To         *time.Time     `form:"to"`

	Page     int `form:"page,default=1" binding:"gte=1"`
	PageSize int `form:"page_size,default=50" binding:"gte=1,lte=100"`
}

// AuditListResponse represents a paginated audit history response.
type AuditListResponse struct {
	Audits     []AuditResponse `json:"audits"`
	Page       int             `json:"page"`
	PageSize   int             `json:"page_size"`
	Total      int64           `json:"total"`
	TotalPages int             `json:"total_pages"`
}

// AuditSummaryResponse provides aggregate audit information.
type AuditSummaryResponse struct {
	Total        int64 `json:"total"`
	Creates      int64 `json:"creates"`
	Reads        int64 `json:"reads"`
	Updates      int64 `json:"updates"`
	Deletes      int64 `json:"deletes"`
	Logins       int64 `json:"logins"`
	Logouts      int64 `json:"logouts"`
	Acknowledged int64 `json:"acknowledged"`
	Escalated    int64 `json:"escalated"`
	FalseAlerts  int64 `json:"false_alerts"`
}