package event

import "time"

type Event struct {
	ID        uint      `gorm:"primaryKey" json:"id"`
	CameraID  uint      `gorm:"not null;index" json:"camera_id"`
	Type      string    `gorm:"not null;index" json:"type"`
	Severity  string    `gorm:"not null;index" json:"severity"`
	Message   string    `gorm:"type:text" json:"message"`
	Timestamp time.Time `gorm:"not null;index" json:"timestamp"`

	// Original event ID generated by the AI engine
	ExternalEventID string `gorm:"index" json:"event_id"`

	// General detection confidence
	Confidence float64 `json:"confidence"`

	// Person information
	PersonID *int `json:"person_id"`

	// Vehicle information
	VehicleID      *int   `json:"vehicle_id"`
	VehiclePresent bool   `json:"vehicle_present"`
	VehicleType    string `json:"vehicle_type"`

	// Restricted zone information
	ZoneStatus string `json:"zone_status"`

	// Object information
	ObjectName    string `json:"object_name"`
	CarriedObject bool   `json:"carried_object"`

	// Number plate information
	PlateNumber     string  `json:"plate_number"`
	PlateCountry    string  `json:"plate_country"`
	PlateConfidence float64 `json:"plate_confidence"`

	// Threat information
	ThreatScore int    `json:"threat_score"`
	ThreatLevel string `json:"threat_level"`

	// Evidence
	EvidenceImage string `json:"evidence_image"`
	IncidentClip  string `json:"incident_clip"`

	CreatedAt time.Time `json:"created_at"`
}